# Swagger e OpenAPI
quarkus.swagger-ui.path=/swagger
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Thalassor
quarkus.smallrye-openapi.info-version=1.0.0

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:8080}
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,role
quarkus.http.cors.access-control-allow-credentials=false

# HTTP
quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}

# RODE NO TERMINAL PARA ABRIR LOCALMENTE

#$env:DB_USERNAME="RM567587"
#$env:DB_PASSWORD="020106"
#$env:DB_URL="jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL"
#$env:CORS_ORIGINS="http://localhost:5173,http://localhost:8080"
